cart/urls.py
from django.urls import path

from cart import views

app_name = "cart"

urlpatterns = [
    path("", views.cart_detail, name="cart_detail"),
    path("add/<int:product_id>", views.cart_add, name="cart_add"),
    path("remove/<int:product_id>", views.cart_remove, name="cart_remove"),
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("cart/",include("cart.urls",namespace="cart")),
    path("", include("shop.urls", namespace="shop")),
    path("order/",include("orders.urls",namespace="orders"))

]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path("create/", views.checkout, name="create_order"),

]

shop/urls.py
from django.conf.urls.static import static
from django.urls import path

from my_shop import settings
from shop import views

app_name = "shop"

urlpatterns = [
    path("", views.show_products, name="all_products"),
    path("<slug:category_slug>/", views.show_products, name="category_products"),
    path("<int:id>/<slug:slug>/", views.product_detail, name="details"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from decimal import Decimal

from django.db import models

# Create your models here.
from shop.models import Product


class Order(models.Model):
    # buyer detials
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=20)

    # order time detials
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # payment
    paid = models.BooleanField(default=False)

    # methods availabe
    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def get_total_cost(self):
        return sum([item.get_total() for item in self.products.all()])

    def __str__(self):
        return f"Order {self.id}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="products")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="order_items")

    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def get_total(self):
        return self.quantity * self.price

    def __str__(self):
        return f"orderItem {self.id}"

shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        verbose_name = 'category'
        verbose_name_plural = "categories"

    def __str__(self):
        return f"Category {self.name}"

    def get_absolute_url(self):
        return reverse("shop:category_products",args=[self.slug])




class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    description = models.TextField(default="No description")
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']

        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return f"Product {self.name}"

    def get_absolute_url(self):
        return reverse("shop:details",args=[self.id,self.slug])

cart/forms.py
from django import forms

from orders.models import Order

choices = [(i, str(i)) for i in range(21)]


class AddProductCartForm(forms.Form):
    quantity = forms.TypedChoiceField(coerce=int, choices=choices)
    override_quantity = forms.BooleanField(widget=forms.HiddenInput, initial=False, required=False)

orders/forms.py
from django import forms
from orders.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name', 'last_name', 'email', 'postal_code', 'address', 'city',
        ]

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.views.decorators.http import require_POST

from orders.models import OrderItem
from shop.models import Product
from .cart import Cart
from .forms import AddProductCartForm


@require_POST
def cart_add(request, product_id):
    """adds or updates a product on the cart"""
    product = Product.objects.get(id=product_id)
    add_form = AddProductCartForm(request.POST)
    cart = Cart(request)
    if add_form.is_valid():
        cd = add_form.cleaned_data
        cart.add(product, cd['quantity'], cd['override_quantity'])
    return redirect("cart:cart_detail")


@require_POST
def cart_remove(request, product_id):
    """removes a product from the cart"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect("cart:cart_detail")


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update'] = AddProductCartForm(initial={'quantity': item['quantity'],
                                                     'override_quantity': True})

    return render(request, "cart_detail.html", {'cart': cart})

orders/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from cart.cart import Cart
from orders.forms import OrderForm
from orders.models import OrderItem, Order
from django.utils import timezone as tz
import datetime


def checkout(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid():
            # preventing multiple same order
            _10_min_ago = tz.now() - datetime.timedelta(minutes=10)
            similiars = Order.objects.filter(created__gte=_10_min_ago,
                                             first_name=request.POST['first_name'],
                                             last_name=request.POST['last_name'])
            if similiars.count() > 0:
                return render(request, "order_created.html", {'already': "1"})
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         quantity=item['quantity'],
                                         price=item['price']
                                         )
            cart.clear()
            return render(request, 'order_created.html',
                          {'order': order})
    else:
        form = OrderForm()
    return render(request, "create_order.html",
                  {'order_form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import AddProductCartForm
# Create your views here.
from shop.models import Product, Category


def show_products(request, category_slug=None):
    category = None
    products = Product.objects.filter(available=True)
    categories = Category.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, "shop/product/list.html", {'products': products,
                                                      'categories': categories,
                                                      'category': category})


def product_detail(request, id, slug):
    form = AddProductCartForm()
    product = get_object_or_404(Product, id=id,
                                slug=slug,
                                available=True)

    return render(request, "shop/product/detail.html", {'product': product, "cart_product_form": form})

cart/templates/cart_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<title>Your Shopping Cart</title>

<h1>Your Shopping Cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit Price</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}"><img src="
                            {% if product.image %}{{ product.image.url }}
                            {% else %}{% static 'image/No_photo.jpg' %}
                            {% endif %}"
                         alt="no poto"></a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                    <form action="{% url 'cart:cart_add' product.id  %}" method="post">
                        {{ item.update.quantity }}
                        {{ item.update.override_quantity }}
                        {% csrf_token %}
                        <input type="submit" value="Update">
                    </form>
                </td>
                <td>
                    <form method="post" action="{% url 'cart:cart_remove' product.id %}">
                        {% csrf_token %}
                        <input type="submit" value="Remove">
                    </form>
                </td>
                <td>{{ product.price }}</td>
                <td>{{ item.total }}</td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<p class="text-right">
    <a  href="{% url 'shop:all_products' %}">Continue shopping</a>
    <a style="margin-left: 15px" class="button" href="{% url 'orders:create_order' %}">Checkout</a>
</p>

orders/templates/create_order.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Making an order{% endblock %}
{% block content %}
    <h1 style="margin-left: 10%;margin-bottom: 0.01px;margin-top: 1px">Checkout</h1>
    <div class="order-info">
        <h2>Your order</h2>
        <ul>
            {% for item in the_cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>{{ item.total }} AFS</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: {{ the_cart.get_total_price }} AFS</p>
    </div>
    <form  method="post" class="order-form">
        {{ order_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Place order"></p>
    </form>
{% endblock %}

orders/templates/order_created.html
{% extends 'shop/base.html' %}
{% block title %}Order done{% endblock %}
<style>
</style>
{% block content %}
    <h1 style="margin-left: 100px;">Thank you for choosing Salsaal</h1>
    {% if not already %}
        <p style="margin-left: 100px;">Your order has been succussfully completed. Your order id is
            <strong>{{ order.id }}.</strong>
        </p>
    {% else %}
        <p style="margin-left: 100px;">This order has already been made.</p>

    {% endif %}
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}My Shop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
<div id="header">
    <a href="/" class="logo">Salsaal Online Shop</a>
</div>
<div id="subheader">
    <div class="cart">
        {% with cart=the_cart %}
            {% if cart|length > 0 %}
                Your cart<a href="{% url 'cart:cart_detail' %}">: {{ cart|length }} item{{ cart|length|pluralize }}, {{ cart.get_total_price }} AFS </a>
            {% elif not order %}
                Your cart is empty
            {% endif %}
        {% endwith %}
    </div>
</div>

{% block content %}

{% endblock %}
</body>
</html>

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'image/No_photo.jpg' %}{% endif %}"
             alt="No Photo">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}"> {{ product.category.name }}</a></h2>
        <p class="price">AFS {{ product.price }}</p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            <input type="submit" value="Add to cart">
            {% csrf_token %}
        </form>
        <p class="description">
            {{ product.description|linebreaks }}
        </p>
    </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{% if category %}{{ category }}{% else %}Products{% endif %}{% endblock %}
{% block content %}
    <div id="sidebar">
        <ul>
            <li {% if not category %}class="selected"{% endif %}><a href="{% url 'shop:all_products' %}">All</a></li>
            {% for cat in categories %}
                <li {% if category.slug == cat.slug %}class="selected" {% endif %}><a
                        href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="
                            {% if product.image %}{{ product.image.url }}{% else %}{% static 'image/No_photo.jpg' %}{% endif %}"
                         alt="No Photo">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>

                AFS {{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}